<?php use Phalcon_Tag as Tag; ?>

<?php echo $this->getContent(); ?>

<div class="profile left">
	<?php echo Tag::form(array('invoices/profile', 'id' => 'profileForm', 'onbeforesubmit' => 'return false')) ?>
		<div class="clearfix">
			<label for="name">Your Full Name:</label>
			<div class="input">
				<?php echo Tag::textField(array("name", "size" => "30", "class" => "span6")) ?>
				<div class="alert" id="name_alert">
					<strong>Warning!</strong> Please enter your full name
				</div>
			</div>
		</div>
		<div class="clearfix">
			<label for="email">Email Address:</label>
			<div class="input">
				<?php echo Tag::textField(array("email", "size" => "30", "class" => "span6")) ?>
				<div class="alert" id="email_alert">
					<strong>Warning!</strong> Please enter your email
				</div>
			</div>
		</div>
		<div class="clearfix">
			<input type="button" value="Update" class="btn btn-primary btn-large btn-info" onclick="Profile.validate()">
			&nbsp;
			<?php echo Tag::linkTo('invoices/index', 'Cancel') ?>
		</div>
	</form>
</div>