<?php echo Phalcon_Tag::form("producttypes/save") ?>

<ul class="pager">
	<li class="previous pull-left">
		<?php echo Phalcon_Tag::linkTo(array("producttypes", "&larr; Go Back")) ?>
	</li>
	<li class="pull-right">
		<?php echo Phalcon_Tag::submitButton(array("Save", "class" => "btn btn-success")) ?>
	</li>
</ul>

<?php echo $this->getContent(); ?>

<div class="center scaffold">
	<h2>Edit product types</h2>


	<input type="hidden" name="id" id="id" value="<?php echo $id ?>" />

	<div class="clearfix">
		<label for="name">Name</label>
		<?php echo Phalcon_Tag::textField(array("name", "size" => 24, "maxlength" => 70)) ?>
	</div>

	</form>
</div>
