<?php echo $this->getContent(); ?>

<div align="right">
	<?php echo Phalcon_Tag::linkTo(array("producttypes/new", "Create Product types", "class" => "btn btn-primary")) ?>
</div>

<?php echo Phalcon_Tag::form(array("producttypes/search")) ?>

<div class="center scaffold">

	<h2>Search product types</h2>

	<div class="clearfix">
		<label for="id">Id</label>
		<?php echo Phalcon_Tag::textField(array("id", "size" => 10, "maxlength" => 10, "type" => "number")) ?>
	</div>

	<div class="clearfix">
		<label for="name">Name</label>
		<?php echo Phalcon_Tag::textField(array("name", "size" => 24, "maxlength" => 70)) ?>
	</div>

	<div class="clearfix">
		<?php echo Phalcon_Tag::submitButton(array("Search", "class" => "btn btn-primary")) ?></td>
	</div>

</div>

</form>
