<?php use Phalcon\Tag as Tag ?>

<?php echo Tag::form("companies/save") ?>

<ul class="pager">
    <li class="previous pull-left">
        <?php echo Tag::linkTo(array("companies", "&larr; Go Back")) ?>
    </li>
    <li class="pull-right">
        <?php echo Tag::submitButton(array("Save", "class" => "btn btn-success")) ?>
    </li>
</ul>

<?php echo $this->getContent() ?>

<div class="center scaffold">
    <h2>Edit companies</h2>

    <input type="hidden" name="id" id="id" value="<?php echo $id ?>" />

    <div class="clearfix">
        <label for="name">Name</label>
        <?php echo Tag::textField(array("name", "size" => 24, "maxlength" => 70)) ?>
    </div>

    <div class="clearfix">
        <label for="telephone">Telephone</label>
        <?php echo Tag::textField(array("telephone", "size" => 10, "maxlength" => 30)) ?>
    </div>

    <div class="clearfix">
        <label for="address">Address</label>
        <?php echo Tag::textField(array("address", "size" => 14, "maxlength" => 40)) ?>
    </div>

    <div class="clearfix">
        <label for="city">City</label>
        <?php echo Tag::textField(array("city", "size" => 14, "maxlength" => 40)) ?>
    </div>

    </form>
</div>
